site_name: pyGCxGC
site_author: YourName
site_description: >-
  pyGCxGC Python package for GCxGC data analysis
nav:
  - Home: index.md
  - Overview:
      - example_docs/intro/why.md
      - example_docs/intro/resources.md
  - Setup:
      - example_docs/setup/prep.md
      - example_docs/setup/name.md
      - example_docs/setup/basics.md
  - Getting started:
      - example_docs/install.md
      - notebooks/Develop_notebook.ipynb

  - Code:
      - example_docs/code/source.md
      - example_docs/code/hints.md
      - example_docs/code/tests.md
  - Documentation:
      - example_docs/mkdocs/docs.md
      - example_docs/mkdocs/build.md
  - GitHub and CI:
      - example_docs/github/commits.md
      - example_docs/github/workflows.md
  - Code Documentation: reference/ # keep me!
  - About:
      - example_docs/about/changelog.md
      - example_docs/about/conduct.md
      - example_docs/about/license.md

repo_url: https://github.com/MyonicS/pyGCxGC/
edit_uri: blob/main/docs/

theme:
  features:
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.path
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - header.autohide
    - toc.follow
  name: material
  palette:
    primary: orange
    scheme: slate

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
          name: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - autorefs
  - offline
  - mkdocs-jupyter
  - mkdocstrings:
