site_name: pyGCxGC
site_author: Sebastian Rejman
site_description: >-
  pyGCxGC Python package for GCxGC data analysis
nav:
  - Home: index.md
  - Getting started:
      - setup/python_start.md
      - setup/install.md
      - notebooks/Develop_notebook.ipynb
  - Resources:
      - notebooks/Develop_notebook.ipynb
      - examples.md
  - Code Documentation: reference/ # keep me!
  - Development:
      - example_docs/about/changelog.md
      - contributing.md
      - roadmap.md
      - example_docs/about/license.md
  - Credits:
      - contributors.md
      - citing.md
      - citing_work.md


repo_url: https://github.com/MyonicS/pyGCxGC/
edit_uri: blob/main/docs/

theme:
  features:
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.path
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - header.autohide
    - toc.follow
  name: material
  palette:
    primary: orange
    scheme: slate
  logo: assets/pyGCxGC_logo-simple.svg


markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      base_path: 
        - '.'
      url_download: true
      url_max_size: 0
      url_timeout: 10.0
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
          name: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
  - autorefs
  - offline
  - mkdocs-jupyter:
      ignore:
        - "docs/gen_ref_pages.py"


extra_css:
  - stylesheets/extra.css