name: tests

env:
  PY_COLORS: 1

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-base:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow writing to repository contents (pushing commits)
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.12"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install pip packages
        run: |
          pip install uv
          uv pip install --system -r tests/requirements.txt .[dev]

      - name: Set coverage core
        run: |
          echo "COVERAGE_CORE=sysmon" >> $GITHUB_ENV

      - name: Run tests with pytest
        run: pytest --cov=pyGCxGC --cov-report=xml --cov-report=html

      - name: Upload coverage reports to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.python-version }}
          path: |
            htmlcov/
            coverage.xml
          retention-days: 7

      - name: Generate coverage badge
        run: |
          pip install coverage-badge
          coverage-badge -o docs/assets/coverage-badge.svg -f

      - name: Commit coverage badge
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/assets/coverage-badge.svg
          git commit -m "chore: update coverage badge [skip ci]" || echo "No changes to commit"
          git push
