name: tests

env:
  PY_COLORS: 1

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-base:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.12"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install pip packages
        run: |
          pip install uv
          uv pip install --system -r tests/requirements.txt .[dev]

      - name: Set coverage core
        run: |
          echo "COVERAGE_CORE=sysmon" >> $GITHUB_ENV

      - name: Run tests with pytest
        run: pytest --cov=pyGCxGC --cov-report=xml --cov-report=html

      - name: Upload coverage reports to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.python-version }}
          path: |
            htmlcov/
            coverage.xml
          retention-days: 7
